---
geometry: margin = 1in
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, eval = FALSE)
```

\pagenumbering{gobble} 

# Stat 340 -- Probability Review

A spam filter is designed by looking at commonly occurring phrases in spam. Suppose that 80% of email is spam. In 10% of the spam emails, the phrase “free money” is used, whereas this phrase is only used in 1% of non-spam emails. 

1. What is the probability an email contains the phrase “free money” and is spam? 

    \vspace{1.5in}

2. Write the event that an email contains the phrase “free money” as the union of disjoint events. 

    \vspace{1.5in}

3. What is the probability that an email contains the phrase “free money?” 

    \vspace{1.5in}

4. A new email has just arrived, which does mention “free money.” What is the probability that it is spam?

\clearpage

# A Bayesian "personality" quiz

**Question 1.** When flipping a fair coin, we say that "the probability of flipping Heads is 0.5." How do you interpret this probability?

1. If I flip this coin over and over, roughly 50% will be Heads.

2. Heads and Tails are equally plausible.

3. Both a and b make sense.


\vspace{1in}

**Question 2.** An election is coming up and a pollster claims that "candidate A has a 0.9 probability of winning." How do you interpret this probability?


1. If we observe the election over and over, candidate A will win roughly 90% of the time.

2. Candidate A is much more likely to win than to lose.

3. The pollster's calculation is wrong. Candidate A will either win or lose, thus their probability of winning can only be 0 or 1.


\vspace{1in}

**Question 3.** Consider two claims. 

- Zuofu claims that he can predict the outcome of a coin flip. To test his claim, you flip a fair coin 10 times and he correctly predicts all 10. 
- Kavya claims that she can distinguish natural and artificial sweeteners. To test her claim, you give her 10 sweetener samples and she correctly identifies each. 

In light of these experiments, what do you conclude?

1. You're more confident in Kavya's claim than Zuofu's claim.

2. The evidence supporting Zuofu's claim is just as strong as the evidence supporting Kavya's claim.


\vspace{1in}

**Question 4.** Suppose that during a recent doctor's visit, you tested positive for a very rare disease. If you only get to ask the doctor one question, which would it be?

1. What's the chance that I actually have the disease?

2. If in fact I don't have the disease, what's the chance that I would've gotten this positive test result?




